### ISSUE TITLE
disco.api.client

### ISSUE THREAD

**Issue by Ferrenom** [JanzenAguila/gachaWaif#1]
$ py GachaWaif.py
Traceback (most recent call last):
  File "GachaWaif.py", line 12, in <module>
    from **disco.api.client** import APIClient
  File "C:\Users\Ferrenom\AppData\Local\Programs\Python\Python36\lib\site-packages\disco\api\client.py", line 10, in <module>
    from disco.api.http import Routes, HTTPClient, to_bytes
  File "C:\Users\Ferrenom\AppData\Local\Programs\Python\Python36\lib\site-packages\disco\api\http.py", line 9, in <module>
    from disco import VERSION as disco_version
ImportError: cannot import name 'VERSION'

was the disco.api.client be discord.api.client? or its really disco?

**Comment by Ferrenom** [comment]
nvm so I got disco-py running tho im kinda stuck at 'APIClient' object has no attribute 'event'
